trigger:
  paths:
    include:
    - vote/*
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: '0f926a20-35e6-4802-a459-a0a6e74daef3'
- name: imageRepository
  value: 'votingservices'
- name: containerRegistry
  value: 'containeracr.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/result/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: vmImageName
  value: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build the images
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'azure-agent'
    steps:
    - task: Docker@2
      displayName: Build the image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push the images
  jobs:
  - job: Push
    displayName: Push
    pool:
      name: 'azure-agent'
    steps:
    - task: Docker@2
      displayName: Build the image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
- stage: Update
  displayName: Update image
  jobs:
  - job: Update
    displayName: Update
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/updateK8sManifests.sh'
        args: 'vote $(imageRepository) $(tag)'

